### ISSUE TITLE
idk

### ISSUE THREAD

**Issue by chsabi** [LlysiX/Guitar-Hero-II-Deluxe-360#1]
Game doesn't open for some reason

**Comment by jnackmclain** [comment]
go to releases of this repo. download all 3 files
run the 2 exes first and complete their installers (default options are fine)
then run the bat. On windows this will pull the repo and get it ready for you.
from then on simply run gh2.bat to pull updates, build an ark, and launch the game.

Consult the readme on the repo for further details.
Wait for alec to post tutorial.
Mac and linux are not supported for building.
